language: cpp
compiler: 
- gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - cmake
before_install:
- sudo pip install codecov
script:
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
- cmake --build .
- ctest 
after_success:
- bash <(curl -s https://codecov.io/bash) -t 39f1709d-439d-4937-ac27-57b952716fb1
